# Generated by Django 5.2.1 on 2025-05-19 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('room_location', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCH', 'Scheduled'), ('CNF', 'Confirmed'), ('ARR', 'Arrived'), ('PRO', 'In Progress'), ('CMP', 'Completed'), ('DEL', 'Delayed'), ('CAN', 'Cancelled'), ('NOS', 'No Show')], default='SCH', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['appointment_datetime'],
            },
        ),
    ]
